name: 'Duolingo.com Stats'
description: 'Dynamically generated duolingo.com stats for your README.md'
author: 'Paul Potaczala'

inputs:
  DUOLINGO_USER_ID:
    description: 'Your duolingo.com user ID'
    default: '730772122'
    required: true
  COMMIT_EMAIL:
    description: "Email used while committing to the repo"
    default: "41898282+github-actions[bot]@users.noreply.github.com"
    required: false
  COMMIT_MSG:
    description: "Commit message used while committing to the repo"
    default: "💬 Updated README with your duolingo stats"
    required: false
  COMMIT_USERNAME:
    description: "Username used while committing to the repo"
    default: "duolingo-stats-bot"
    required: false
  FILE_NAME:
    description: "Define a specific file in your repo"
    default: "README.md"
    required: false
  SHOW_LANGUAGES:
    description: "Toggle the languages table"
    default: "true"
    required: false
  SHOW_FROM_ENGLISH:
    description: "Determines, whether \" (from English)\" should be appended to languages learnt from English, similarly to learning from other languages"
    default: "false"
    required: false
  SHOW_LEAGUE:
    description: "Set, whether the user table should show the current league"
    default: "true"
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'green'
